## Read Diseases

In [3]:
import pandas as pd
disease = pd.read_csv('../Datasets/disease/icd10_2019 - Copy.csv')

In [4]:
disease.head()

,Unnamed: 0,url,chapter,domain,sub-code,definition
0,1.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00,Cholera
1,2.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00.0,"Cholera due to Vibrio cholerae 01, biovar chol..."
2,3.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00.1,"Cholera due to Vibrio cholerae 01, biovar eltor"
3,4.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00.9,"Cholera, unspecified"
4,5.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A01,Typhoid and paratyphoid fevers

## Clean Diseases

In [5]:
disease = disease[disease['definition'].duplicated() == False]

In [6]:
disease.shape

(6, 6)

In [7]:
disease.dropna(subset=['definition'], inplace=True)

In [8]:
disease = disease[disease['sub-code'].str.contains(r'\.')]

In [9]:
disease = disease[~disease["definition"].str.contains("Other|Unspecified|not elsewhere", case=False)]

In [10]:
len(disease['definition'].unique())

2

In [11]:
disease[disease['definition'].duplicated() == True]['definition'].sort_values().values

array([], dtype=object)

In [12]:
disease.head()

,Unnamed: 0,url,chapter,domain,sub-code,definition
1,2.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00.0,"Cholera due to Vibrio cholerae 01, biovar chol..."
2,3.0,https://icd.who.int/browse10/2019/en#/A00-A09,Chapter I\r\nCertain infectious and parasitic ...,Intestinal infectious diseases\r\n(A00-A09),A00.1,"Cholera due to Vibrio cholerae 01, biovar eltor"

In [13]:
disease.shape

(2, 6)

In [14]:
import re
disease_dic = []
for index, i in disease.iterrows():
    d = {
    "Chapter": re.search(r"\n(.*)\r", i['chapter']).group(1) if re.search(r"\n(.*)\r", i['chapter']) else None,
    "Domain": re.sub(r'[\r\n]+|\s*\(.*?\)', '', i['domain']).strip(),
    "Disease": i['definition'],
    "Sub-code": i['sub-code'],
    }
    disease_dic.append(d)

In [15]:
print(disease_dic[1]['Chapter'])

Certain infectious and parasitic diseases

In [16]:
print(disease_dic[1]['Domain'])

Intestinal infectious diseases

## Scrape Data from 🇩🇪 Federal Ministry of Health

In [17]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()
for disease in disease_dic:
    driver.get("https://gesund.bund.de/en/icd-code-suche")
    disease["Result Link"] = []
    search = driver.find_element(By.CLASS_NAME, 'input--text')
    button = driver.find_element(By.XPATH, '//*[@id="app"]/header/a-header/div/div[1]/div/div[3]/form/a-auto-suggest/button[2]')
    search.send_keys(f"{disease['Sub-code']} {disease['Disease']}")
    button.click()
    time.sleep(2)
    res = driver.find_elements(By.CLASS_NAME, 'm-search-result__item-link')
    disease["Result Link"].append([r.get_attribute("href") for r in res][0])
driver.quit()

In [18]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()

for disease in disease_dic:
    disease["Article"] = []
    for link in disease["Result Link"]:
        driver.get(link)
        time.sleep(2)
        article = driver.find_element(By.XPATH, '//*[@id="standard-textseite-headline-h1"]/section[1]/div[1]')
        disease["Article"].append({
        "source": "Federal Ministry of Health",
        "content": article.text
    })
driver.quit()

In [19]:
import json

with open("diseases.json", "w", encoding="utf-8") as f:
    json.dump(disease_dic, f, ensure_ascii=False, indent=4)

## Scrape Data from Medlineplus

In [20]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()

for disease in disease_dic:
    driver.get("https://medlineplus.gov/all_healthtopics.html")
    search = driver.find_element(By.ID, 'searchtext_primary')
    button = driver.find_element(By.XPATH, '/html/body/div[1]/header/div/div[3]/div[2]/form/div/div[2]/button')
    search.send_keys(disease['Disease'])
    button.click()
    time.sleep(2)
    res = driver.find_elements(By.CLASS_NAME, 'title')
    for r in res:
        if r.get_attribute("href") and "medlineplus.gov" in r.get_attribute("href"):
            disease["Result Link"].append(r.get_attribute("href"))
            print(r.get_attribute("href"))
driver.quit()

In [ ]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()

for disease in disease_dic:
    for link in disease["Result Link"]:
      if link and "medlineplus.gov" in link:
        driver.get(link)
        time.sleep(2)
        article = driver.find_element(By.ID, 'mplus-content')
        disease["Article"].append({
    "source": "medlineplus",
    "content": article.text
})
driver.quit()

In [22]:
import json

with open("diseases.json", "w", encoding="utf-8") as f:
    json.dump(disease_dic, f, ensure_ascii=False, indent=4)

## Scrape Data from CDC

In [23]:
driver = webdriver.Chrome()
for disease in disease_dic:        
        driver.get("https://search.cdc.gov/search/")
        time.sleep(2)
        search = driver.find_element(By.XPATH, '/html/body/main/div/div/div/div/div[1]/div[1]/div[1]/div[1]/div/input[1]')
        button = driver.find_element(By.CLASS_NAME, 'cdc-fa-magnifying-glass')
        search.send_keys(disease['Disease'])
        button.click()
        time.sleep(2)
        res = driver.find_elements(By.CLASS_NAME, 'result')
        for el in res:
            a_tag = el.find_element(By.TAG_NAME, "a")
            if a_tag.get_attribute("href") and "https://wwwnc.cdc.gov/eid/article/" in a_tag.get_attribute("href"):
                link = a_tag.get_attribute("href")
                disease["Result Link"].append(link)
driver.quit()

In [24]:
from selenium import webdriver
from selenium.webdriver.common.by import By
import time
driver = webdriver.Chrome()

for disease in disease_dic:
    for link in disease["Result Link"]:
      if link and "https://wwwnc.cdc.gov/eid/article/" in link:
        driver.get(link)
        time.sleep(2)
        try:
          article = driver.find_element(By.ID, 'mainbody')
          disease["Article"].append({
          "source": "CDC",
          "content": article.text
          })
          print(article.text)
        except:
            continue
driver.quit()

To the Editor: Vibrio cholerae O1, the causative agent of cholera, has 2 biotypes (classical and El Tor), which have traditionally been distinguished by phenotypic tests and by genetic differences in the major toxin-coregulated pilus (TCP) gene, the tcpA allele of the TCP cluster (1), the rstR region (regulatory region for phage lysogeny) of CTX phages (2), the type of cholera toxin (CT) produced, and the infection pattern of the disease they cause. However, 3 variants of the El Tor biotype have been described recently: Matlab (a place in Bangladesh) variants in 2002 (3), which could not be biotyped because they have a mixture of both classical and El Tor (4), Mozambique variant in 2004–2005, which has a typical El Tor genome but a tandem repeat of the classical CTX prophage in the small chromosome (5), and the altered El Tor type (a typical El Tor biotype and an El Tor CTX prophage that produces CT of the classical type) predominant in Bangladesh since 2001 (6). Hybrid vibrios have also been described in other regions of Asia and Africa (7).
CT, encoded by the ctxA and ctxB genes, is the principal toxin produced by V. cholerae O1 and O139. Methods for differentiating the biotype-specific CT-B subunit of V. cholerae O1 include sequencing the ctxB gene, performing an ELISA wth a monoclonal antibody specific to the classical or El Tor CT, or by using a mismatch amplification mutation assay (MAMA)–PCR to distinguish between 2 kinds of ctxB genes. This assay detects sequence polymorphisms based on nt position 203 of the ctxB gene (8).
In Punjab and Haryana states of northern India, during July–September 2007, 6 clusters of cholera outbreak were identified. A total of 745 case-patients were admitted to local government hospitals; the cholera attack rate was 183/1,000 population. Four deaths were reported (case-fatality rate 0.5%). The number of cases per cluster varied from 15 to 400, and adults were primarily affected (74%); 20% of patients had severe dehydration. V. cholerae O1 Ogawa was confirmed from stool cultures by using standard isolation, biochemical, and serotyping methods. Twenty-six isolates were phenotypically and genotypically characterized according to biotype. Phenotypic characterization included the Voges-Proskauer reaction, polymyxin B (50 U) susceptibility, chick cell agglutination, and sheep erythrocyte hemolysis; all isolates were confirmed as El Tor biotype. Genotypic characterization included PCR assays for ctxA and tcpA (2), rstR (3), and ctxB (8). All strains were toxigenic because each carried the ctxA gene. All strains also carried El Tor–specific tcpA (472 bp) and rstR genes (500 bp). MAMA-PCR showed the ctxB gene of both El Tor and the classical type in 21 (80%) of 26 isolates tested.
Similarly, we also tested 20 available isolates from the 2002 outbreak and 4 and 19 sporadic isolates from 2003 and 2004, respectively; all were phenotypically and genotypically confirmed as El Tor and had only ctxB of the El Tor type. Of 53 water samples tested during the 2007 outbreak, 4 grew V. cholerae. Three samples were confirmed to be non-O1, non-O139 strains. Only 1 isolate was V. cholerae O1, which was positive for tcp, ctxA, and ctxB of both classical and El Tor types (Table).
During the cholera outbreak of 2002 in Chandigarh (9), only 1 death was reported (case-fatality rate, <0.01%); the attack rate was 20/1,000, 58.6% were children, and only 10% had severe dehydration. Before the most recent outbreak, the affected regions of Panjab and Haryana (Ambala, Nurpur, Kurali, Mohali, Panchkula, and Raili) had been free of cholera outbreaks since 1994, though sporadic cases had been reported. The 4 deaths from cholera in 2007, along with adult preponderance, high attack rate, more severe illness, and 6 different clusters, point towards a change in the disease’s epidemiology. This change may be related to circulation of the hybrid vibrios in this region. In Bangladesh, all strains of V. cholerae O1 examined since 2001 belong to the altered El Tor type (6), which produces CT of the classical type. This altered type has replaced the seventh pandemic strain of the El Tor biotype that produced CT of the El Tor type, which indicates that a cryptic change has occurred in the seventh pandemic El Tor biotype strains of V. cholerae O1.
Newly emerged variants from Bangladesh (8) have the genetic makeup of El Tor with ctxB gene of only classical, whereas our strains are unique in having ctxB of both the classical and El Tor biotypes. Our strains appear to be different from the Mozambique variant V. cholerae O1 (10), which has rstR of the classical type, in that our strains have rstR of only the El Tor type. Of 5 Matlab variants analyzed with MAMA-PCR, 3 had classical ctxB and 2 had El Tor type. Our study highlights the different genetic recombinations possible in V. cholerae and the epidemiologic role of these recombinations.
Top
External Link
To the Editor. Cholera, caused by Vibrio cholerae, continues to affect millions of persons in disease-endemic areas where safe drinking water is scarce and sanitation is poor. Of 7 cholera pandemics recorded since 1817, V. cholerae serogroup O1 classical (CL) biotype was associated with the sixth, whereas the seventh (ongoing) pandemic was initiated by V. cholerae O1 biotype El Tor (ET), which displaced CL in the early 1960s (1). During 1992–1993, a V. cholerae non-O1 serogroup, designated V. cholerae O139 synonym Bengal, initiated cholera epidemics in India and Bangladesh by transiently displacing V. cholerae O1 ET biotype (2). V. cholerae O139 was less frequently associated with cholera in Bangladesh than V. cholerae ET in 1994 and the years following, until 2005 (3); it has been undetected since then. Meanwhile, V. cholerae ET has shown genetic changes since 2001, and isolates carry the ctxB gene of the CL biotype (ctxBCL) in Bangladesh (4). Although the genetic transition from ctxBET to ctxBCL was observed during 1998–1999 for V. cholerae O139 (5), V. cholerae strains carrying ctxBET were considered extinct, i.e., undetected for about a decade.
During June 2010–December 2012, the International Centre for Diarrheal Disease Research, Bangladesh (ICDDR,B) systematically conducted ongoing epidemiologic ecologic surveillance in Dhaka, Chhatak, and Mathbaria and isolated V. cholerae strains (n = 500 [clinical/environmental]: Dhaka [n = 110/94], Mathbaria [n = 90/79], Chhatak [n = 111/16]). Of the 500 V. cholerae isolates, 496 were confirmed as O1 and 4 as O139 Bengal, on the basis of serologic, phenotypic, and genetic properties (3,6–8). All V. cholerae O1 and O139 isolates were positive for ctxA, tlc, ace, and zot and possessed ET biotype–specific markers tcpAET, hlyAET, and rtxC. Mismatch amplification mutation assay–PCR (9) demonstrated ctxBCL allele in 492 V. cholerae O1 ET strains (altered ET), whereas ctxBET was found in 8 isolates (4 V. cholerae O1 ET and 4 V. cholerae O139).
Nucleotide sequencing of ctxB showed that the translated sequences of V. cholerae O1 and O139 strains carrying ctxBET were identical to those of the ET reference strain N16961 (GenBank accession no. NC_002505), with tyrosine and isoleucine at positions 39 and 68, respectively, as opposed to altered ET, which possesses histidine and threonine at positions 39 and 68, respectively (4). PCR additionally showed that the V. cholerae O1 and O139 Bengal strains carrying ctxBET had the ET biotype–specific RS1 element gene rstC and repressor gene rstRET, suggesting prototype ET attributes (7).
Three V. cholerae strains carrying ctxBET were first isolated in 2011 from surface water: one O1 strain and one O139 strain from Mathbaria and one O1 strain from Chhatak. In 2012, V. cholerae O1 carrying ctxBET was isolated from cholera patients in Mathbaria and Chhatak (n = 1 each). Also, 3 O139 strains carrying ctxBET were isolated from surface water in Dhaka. The confirmed V. cholerae O1 and O139 Bengal strains carrying ctxBET were of particular interest because altered ET strains carrying ctxBCL have been deemed the cause of endemic cholera in Bangladesh since 2001 (4) and globally (10).
Figure. . DNA fingerprinting patterns of Vibrio cholerae. Dendrogram was prepared by Dice similarity coefficient and UPGMA (unweighted pair-group method with arithmetic mean) clustering methods by using pulsed-field gel electrophoresis (PFGE) images...
V. cholerae strains carrying ctxBET were closely related to the pre-2001 V. cholerae strains carrying ctxBET, as were the O139 Bengal strains carrying ctxBET. Two lines of evidence support this close relationship. First, the antimicrobial drug resistance patterns of 3 of the V. cholerae O139 strains isolated in Dhaka during 2012 were resistant to trimethoprim/sulfamethoxazole (25 µg), whereas the remaining O139 and 4 O1 strains were susceptible to all drugs tested, including azithromycin (15 µg), ciprofloxacin (5 µg), gentamicin (10 µg), ampicillin (10 µg), tetracycline (30 µg), and erythromycin (15 µg). Second, pulsed-field gel electrophoresis (PFGE) of NotI-digested genomic DNA showed identical banding patterns for the 4 V. cholerae O1 strains carrying ctxBET and the pre-2001 ET strains, including N16961, and the DNA pattern differed from that of the altered ET associated with endemic cholera in Bangladesh (Figure). All 4 V. cholerae O139 strains had typical O139 Bengal banding patterns, shown by PFGE, except that 1 strain had an extra band (Figure). Comparison of PFGE patterns with those of previously isolated V. cholerae O139 strains (1993–2005) showed that recently isolated strains (2011–2012) belonged to 1 of the ancient clones, suggesting that the strain has been present in Bangladesh since 1993 (Figure).
In conclusion, we provide evidence of the coexistence of V. cholerae O1 and O139 strains, which shows that strains carrying ctxBET, not isolated for approximately a decade in Bangladesh, have again been isolated (3). Although the epidemiologic importance of the observed genetic change in the ctxB is yet to be understood, the finding of V. cholerae strains carrying ctxBET in surface water of Bangladesh in 2011 and in association the following year with cholera may be yet another turning point, considering that the global pattern of cholera is changing rapidly.
Top
External Link
Vibrio cholerae O1 has been responsible for several cholera outbreaks in developing countries. During 1992, a novel serogroup, O139, caused cholera outbreaks in India and other countries in Asia (1). These events have shown that serogroups other than O1 have major epidemiologic roles in cholera. V. cholerae O1 and O139 serogroups produce cholera toxin (CT), a critical virulence factor and express toxin coregulated pilus (TCP), which are responsible for secretory diarrhea and intestinal colonization, respectively. Serogroups other than O1 and O139 are designated as V. cholerae non-O1, non-O139, or nonagglutinating vibrios (NAGs); such serogroups have >200 somatic (O) antigens (2) and mostly lack CT- and TCP-coding genes.
Toxigenic and nontoxigenic NAGs have caused several diarrhea outbreaks in India and other countries, including Haiti (3–6). In non–CT-producing NAGs, other virulence factors such as heat-stable enterotoxin (Stn), hemolysin (HlyA), repeat in toxin (RTX), and type 3 secretion systems (TTSS) have major roles in causing infections (7). In this study, we analyzed clinical characteristics of hospitalized patients with diarrhea infected with NAGs and screened strains for antimicrobial drug susceptibility, virulence genes, and genetic relatedness.
The Study
During 2002–2010, a total of 12,719 fecal specimens were collected, which represented every fifth hospitalized diarrhea patient at the Infectious Diseases Hospital in Kolkata and all children at the outpatient unit at B.C. Roy Memorial Hospital for Children in Kolkata. Fecal specimens were screened for V. cholerae and other enteric pathogens as described (8). NAGs were serotyped by using 206 polyclonal O antisera according to the protocol developed at the National Institute of Infectious Diseases (Tokyo, Japan) (2).
Antimicrobial drug susceptibility assays were performed by using the disk diffusion method and commercially available disks (Becton Dickinson, Sparks Glencoe, MD, USA), according to standards of the Clinical and Laboratory Standards Institute (9). Because these standards do not include interpretive criteria for V. cholerae, breakpoints for Enterobacteriaceae were adopted. Escherichia coli ATCC 25922 was used as a quality-control strain.
Simplex and multiplex PCRs were performed by using published methods specific for ctxA, tcpA, rtxA, rtxC, stn, and hlyA genes (classical/El Tor) and the TTSS-coding genes (7). Pulsed-field gel electrophoresis was performed according to the PulseNet standardized protocol for V. cholerae (www.pulsenetinternational.org/SiteCollectionDocuments/pfge/5.71_2009_PNetStandProtVcholerae.pdf. Gel Compare II software (Applied Maths NV, Sint-Martens-Latem, Belgium) was used for comparison of electrophoresis patterns. This software uses a Dice similarity index and contains an unweighted pair group with arithmetic mean method.
Of the 12,719 diarrhea feces specimens screened, 2,206 (17.3%) contained V. cholerae, which included V. cholerae O1 in 1,841 (83.4%), and O139 in 84 (3.8%). In the remaining 281 (12.7%) specimens, V. cholerae strains did not agglutinate with serogroups O1 or O139. This result was confirmed by species-specific ompW PCR, which included strains collected during 2003 (7). Among 281 strains, 175 (62.3%) NAGs were the only enteric pathogen found, and 106 (37.7%) of those NAGs were found with other enteric pathogens. The isolation frequency of NAGs ranged from 1.2% to 3.2% (Table 1).
Although V. cholerae O1 is highly prevalent in Kolkata, more NAGs were detected than in our previous study (10). A total of 224 (79.7%) strains were categorized into 80 serogroups; the remaining 57 (20.3%) were untypeable. Among typeable serogroups, 14 (6.2%) strains belonged to the O37 serogroup, and 11 (4.9%) each belonged to serogroups O6 and O34. Serogroups O97 (4.5%), O11 (3.6%), and O59 (3.1%) were also identified in this study. Although serogroups O11, O35, and O37 showed a lower prevalence, their prevalence was higher among patients with diarrhea in Kolkata (7,10). The prevalence rate of NAGs (≈2%) in Kolkata is similar to that in the Haizhu District of Guangzhou, China (11). However, the number of serogroups identified in China (26 serogroups) was less than in our study (80 serogroups).
Among age groups of patients, NAGs were detected mostly in patients >5 years of age (>72%) than in those <5 years of age (≈28%) (Table 2). NAGs produce a spectrum of gastrointestinal symptoms ranging from asymptomatic infection to severe cholera-like illness or bloody diarrhea. In this study, most (70%) patients had watery diarrhea, which was similar to that for patients with cholera and those exclusively infected by NAGs (Table 2). Other clinical symptoms, such as dehydration status (22.3%) and fever (41.1%), were also high in patients with a single infection. In patients with mixed infections, bloody diarrhea (23.6%) and abdominal pain (41.5%) were the 2 major symptoms (Table 2), perhaps because >1 pathogen was involved.
Most NAGs were resistant to nalidixic acid (57.6%), ampicillin (55.5%), furazolidone (36.6%), and streptomycin (32.4%) and highly susceptible to gentamicin (96%), tetracycline (80%), and chloramphenicol (80.4%). During 1992–1997, antimicrobial drug resistance was high among V. cholerae isolated in Kolkata (12). In this study, patterns of antimicrobial drug resistance in NAGs were different than those in previous reports (10,12). This finding might be caused by discontinuation of ineffective antimicrobial drugs, such as co-trimoxazole and furazolidone, rational use of fluoroquinolones, and introduction of azithromycin for treating diarrhea.
Top
Conclusions
Unlike our previous study (7), in this study, factors involved in the virulence of NAGs were not comprehensively elucidated in the study region. Unlike V. cholerae O1/O139, the pathogenicity of NAGs has been associated with >1 virulence factor (7,10). All NAGs lacked ctxA and El Tor tcpA genes. However, 6 (2.1%) strains had the tcpA gene; in 5 of them it was the only virulence gene detected. Most (94%) strains had the gene encoding El Tor type hemolysin, followed by rtxA (91.4%) and rtxC (75%) genes; only 5 (1.8%) had the stn gene. The RTX family includes a group of protein toxins produced by gram-negative bacteria, including V. cholerae with hemolytic, leukotoxic, and actin cross-linking activities, which may play a role in virulence (13). In this study, prevalence of NAGs that have genes encoding TTSS as the only virulence factor (41 cases) was higher than in Bangladesh and Argentina (14,15).
Figure. . . NotI restriction patterns of genomic DNA of representative Vibrio cholerae non-O1, non-O139 strains, Kolkata, India. Dendrogram was generated by using the unweighted pair group with arithmetic mean method.
Strains containing hlyA, rtxA, and rtxC genes were predominant, followed by strains containing hlyA-rtxA-rtxC-TTSS and hlyA-rtxA genes (Table 3). Some gene combinations, such as hlyA-rtxA-rtxC-TTSS, hlyA-rtxA-rtxC, and hlyA-rtxA, were detected predominantly NAGs as the only virulence factor genes (Table 3). However, there was no correlation between type of serogroup and prevalence of putative virulence gene(s). Pulsed-field electrophoresis profiles of 70 strains representing the predominant serogroups showed distinct patterns (overall similarity ≈70%) (Figure). There was no profile match among strains belonging to the same serogroup.
Prevalence of NAGs associated with severe traits of infection indicates the role of these pathogens in cholera. The pathogenic mechanism of NAGs is multifarious; there are several virulence factors in genetically distinct strains. On the basis of our results, current antimicrobial drug therapy in the clinical management of NAG-mediated diarrhea can be continued. Further epidemiologic studies are needed to determine the ecology, virulence factors, and public health role of NAGs.
Top
Ms Devarati Dutta is a doctoral candidate at the National Institute of Cholera and Enteric Diseases, Kolkata, India. Her main research interest is the pathogenesis and molecular biology of enteric vibrios.
Top
External Link
Vibrio cholerae O139 Bengal first emerged during 1992 and 1993 and caused large epidemics of cholera in Bangladesh, India, and neighboring countries (1–3). This new strain initially displaced the existing V. cholerae O1 strains. During 1994 to the middle of 1995, in most northern and central areas of Bangladesh, the O139 vibrios were replaced by a new clone of V. cholerae O1 of the El Tor biotype, whereas in the southern coastal regions the O139 vibrios continued to exist (4–6). During late 1995 and 1996, cases of cholera attributable to both V. cholerae O1 and O139 were again detected in various regions of Bangladesh. Since 1996, cholera in Bangladesh has been caused mostly by V. cholerae O1 of the El Tor biotype; only a few cases have been attributable to O139 serogroup strains. The epidemiology of cholera in Bangladesh changed again recently, and a large outbreak of cholera caused predominantly by V. cholerae O139 occurred in the capital city Dhaka and adjoining areas.

## Save Scraped Data

In [25]:
import json

with open("diseases.json", "w", encoding="utf-8") as f:
    json.dump(disease_dic, f, ensure_ascii=False, indent=4)

## Load Data

In [26]:
import pandas as pd
data = pd.read_json("diseases.json")

## Explore Data

In [27]:
data.head()

,Chapter,Domain,Disease,Sub-code,Result Link,Article
0,Certain infectious and parasitic diseases,Intestinal infectious diseases,"Cholera due to Vibrio cholerae 01, biovar chol...",A00.0,[https://gesund.bund.de/en/icd-code-suche/a00-...,"[{'source': 'Federal Ministry of Health', 'con..."
1,Certain infectious and parasitic diseases,Intestinal infectious diseases,"Cholera due to Vibrio cholerae 01, biovar eltor",A00.1,[https://gesund.bund.de/en/icd-code-suche/a00-...,"[{'source': 'Federal Ministry of Health', 'con..."

In [28]:
word = ""
for articles in data["Article"]:
    for article in articles:
            word = word + "" + article['content'].lower()

In [29]:
word

'you have cholera.\ncholera is caused by bacteria. its symptoms include severe runny diarrhea. vomiting is another symptom. the vomit can be watery, but also bloody. the diarrhea and vomiting results in a great deal of fluid and important nutrients being lost. this can make you very sick.\ncholera can be transmitted through contaminated water and food.to the editor: vibrio cholerae o1, the causative agent of cholera, has 2 biotypes (classical and el tor), which have traditionally been distinguished by phenotypic tests and by genetic differences in the major toxin-coregulated pilus (tcp) gene, the tcpa allele of the tcp cluster (1), the rstr region (regulatory region for phage lysogeny) of ctx phages (2), the type of cholera toxin (ct) produced, and the infection pattern of the disease they cause. however, 3 variants of the el tor biotype have been described recently: matlab (a place in bangladesh) variants in 2002 (3), which could not be biotyped because they have a mixture of both classical and el tor (4), mozambique variant in 2004–2005, which has a typical el tor genome but a tandem repeat of the classical ctx prophage in the small chromosome (5), and the altered el tor type (a typical el tor biotype and an el tor ctx prophage that produces ct of the classical type) predominant in bangladesh since 2001 (6). hybrid vibrios have also been described in other regions of asia and africa (7).\nct, encoded by the ctxa and ctxb genes, is the principal toxin produced by v. cholerae o1 and o139. methods for differentiating the biotype-specific ct-b subunit of v. cholerae o1 include sequencing the ctxb gene, performing an elisa wth a monoclonal antibody specific to the classical or el tor ct, or by using a mismatch amplification mutation assay (mama)–pcr to distinguish between 2 kinds of ctxb genes. this assay detects sequence polymorphisms based on nt position 203 of the ctxb gene (8).\nin punjab and haryana states of northern india, during july–september 2007, 6 clusters of cholera outbreak were identified. a total of 745 case-patients were admitted to local government hospitals; the cholera attack rate was 183/1,000 population. four deaths were reported (case-fatality rate 0.5%). the number of cases per cluster varied from 15 to 400, and adults were primarily affected (74%); 20% of patients had severe dehydration. v. cholerae o1 ogawa was confirmed from stool cultures by using standard isolation, biochemical, and serotyping methods. twenty-six isolates were phenotypically and genotypically characterized according to biotype. phenotypic characterization included the voges-proskauer reaction, polymyxin b (50 u) susceptibility, chick cell agglutination, and sheep erythrocyte hemolysis; all isolates were confirmed as el tor biotype. genotypic characterization included pcr assays for ctxa and tcpa (2), rstr (3), and ctxb (8). all strains were toxigenic because each carried the ctxa gene. all strains also carried el tor–specific tcpa (472 bp) and rstr genes (500 bp). mama-pcr showed the ctxb gene of both el tor and the classical type in 21 (80%) of 26 isolates tested.\nsimilarly, we also tested 20 available isolates from the 2002 outbreak and 4 and 19 sporadic isolates from 2003 and 2004, respectively; all were phenotypically and genotypically confirmed as el tor and had only ctxb of the el tor type. of 53 water samples tested during the 2007 outbreak, 4 grew v. cholerae. three samples were confirmed to be non-o1, non-o139 strains. only 1 isolate was v. cholerae o1, which was positive for tcp, ctxa, and ctxb of both classical and el tor types (table).\nduring the cholera outbreak of 2002 in chandigarh (9), only 1 death was reported (case-fatality rate, <0.01%); the attack rate was 20/1,000, 58.6% were children, and only 10% had severe dehydration. before the most recent outbreak, the affected regions of panjab and haryana (ambala, nurpur, kurali, mohali, panchkula, and raili) had been free of cholera outbreaks since 1994, though sporadic cases had been reported. the 4 deaths from cholera in 2007, along with adult preponderance, high attack rate, more severe illness, and 6 different clusters, point towards a change in the disease’s epidemiology. this change may be related to circulation of the hybrid vibrios in this region. in bangladesh, all strains of v. cholerae o1 examined since 2001 belong to the altered el tor type (6), which produces ct of the classical type. this altered type has replaced the seventh pandemic strain of the el tor biotype that produced ct of the el tor type, which indicates that a cryptic change has occurred in the seventh pandemic el tor biotype strains of v. cholerae o1.\nnewly emerged variants from bangladesh (8) have the genetic makeup of el tor with ctxb gene of only classical, whereas our strains are unique in having ctxb of both the classical and el tor biotypes. our strains appear to be different from the mozambique variant v. cholerae o1 (10), which has rstr of the classical type, in that our strains have rstr of only the el tor type. of 5 matlab variants analyzed with mama-pcr, 3 had classical ctxb and 2 had el tor type. our study highlights the different genetic recombinations possible in v. cholerae and the epidemiologic role of these recombinations.\ntop\nexternal linkto the editor. cholera, caused by vibrio cholerae, continues to affect millions of persons in disease-endemic areas where safe drinking water is scarce and sanitation is poor. of 7 cholera pandemics recorded since 1817, v. cholerae serogroup o1 classical (cl) biotype was associated with the sixth, whereas the seventh (ongoing) pandemic was initiated by v. cholerae o1 biotype el tor (et), which displaced cl in the early 1960s (1). during 1992–1993, a v. cholerae non-o1 serogroup, designated v. cholerae o139 synonym bengal, initiated cholera epidemics in india and bangladesh by transiently displacing v. cholerae o1 et biotype (2). v. cholerae o139 was less frequently associated with cholera in bangladesh than v. cholerae et in 1994 and the years following, until 2005 (3); it has been undetected since then. meanwhile, v. cholerae et has shown genetic changes since 2001, and isolates carry the ctxb gene of the cl biotype (ctxbcl) in bangladesh (4). although the genetic transition from ctxbet to ctxbcl was observed during 1998–1999 for v. cholerae o139 (5), v. cholerae strains carrying ctxbet were considered extinct, i.e., undetected for about a decade.\nduring june 2010–december 2012, the international centre for diarrheal disease research, bangladesh (icddr,b) systematically conducted ongoing epidemiologic ecologic surveillance in dhaka, chhatak, and mathbaria and isolated v. cholerae strains (n = 500 [clinical/environmental]: dhaka [n = 110/94], mathbaria [n = 90/79], chhatak [n = 111/16]). of the 500 v. cholerae isolates, 496 were confirmed as o1 and 4 as o139 bengal, on the basis of serologic, phenotypic, and genetic properties (3,6–8). all v. cholerae o1 and o139 isolates were positive for ctxa, tlc, ace, and zot and possessed et biotype–specific markers tcpaet, hlyaet, and rtxc. mismatch amplification mutation assay–pcr (9) demonstrated ctxbcl allele in 492 v. cholerae o1 et strains (altered et), whereas ctxbet was found in 8 isolates (4 v. cholerae o1 et and 4 v. cholerae o139).\nnucleotide sequencing of ctxb showed that the translated sequences of v. cholerae o1 and o139 strains carrying ctxbet were identical to those of the et reference strain n16961 (genbank accession no. nc_002505), with tyrosine and isoleucine at positions 39 and 68, respectively, as opposed to altered et, which possesses histidine and threonine at positions 39 and 68, respectively (4). pcr additionally showed that the v. cholerae o1 and o139 bengal strains carrying ctxbet had the et biotype–specific rs1 element gene rstc and repressor gene rstret, suggesting prototype et attributes (7).\nthree v. cholerae strains carrying ctxbet were first isolated in 2011 from surface water: one o1 strain and one o139 strain from mathbaria and one o1 strain from chhatak. in 2012, v. cholerae o1 carrying ctxbet was isolated from cholera patients in mathbaria and chhatak (n = 1 each). also, 3 o139 strains carrying ctxbet were isolated from surface water in dhaka. the confirmed v. cholerae o1 and o139 bengal strains carrying ctxbet were of particular interest because altered et strains carrying ctxbcl have been deemed the cause of endemic cholera in bangladesh since 2001 (4) and globally (10).\nfigure. . dna fingerprinting patterns of vibrio cholerae. dendrogram was prepared by dice similarity coefficient and upgma (unweighted pair-group method with arithmetic mean) clustering methods by using pulsed-field gel electrophoresis (pfge) images...\nv. cholerae strains carrying ctxbet were closely related to the pre-2001 v. cholerae strains carrying ctxbet, as were the o139 bengal strains carrying ctxbet. two lines of evidence support this close relationship. first, the antimicrobial drug resistance patterns of 3 of the v. cholerae o139 strains isolated in dhaka during 2012 were resistant to trimethoprim/sulfamethoxazole (25 µg), whereas the remaining o139 and 4 o1 strains were susceptible to all drugs tested, including azithromycin (15 µg), ciprofloxacin (5 µg), gentamicin (10 µg), ampicillin (10 µg), tetracycline (30 µg), and erythromycin (15 µg). second, pulsed-field gel electrophoresis (pfge) of noti-digested genomic dna showed identical banding patterns for the 4 v. cholerae o1 strains carrying ctxbet and the pre-2001 et strains, including n16961, and the dna pattern differed from that of the altered et associated with endemic cholera in bangladesh (figure). all 4 v. cholerae o139 strains had typical o139 bengal banding patterns, shown by pfge, except that 1 strain had an extra band (figure). comparison of pfge patterns with those of previously isolated v. cholerae o139 strains (1993–2005) showed that recently isolated strains (2011–2012) belonged to 1 of the ancient clones, suggesting that the strain has been present in bangladesh since 1993 (figure).\nin conclusion, we provide evidence of the coexistence of v. cholerae o1 and o139 strains, which shows that strains carrying ctxbet, not isolated for approximately a decade in bangladesh, have again been isolated (3). although the epidemiologic importance of the observed genetic change in the ctxb is yet to be understood, the finding of v. cholerae strains carrying ctxbet in surface water of bangladesh in 2011 and in association the following year with cholera may be yet another turning point, considering that the global pattern of cholera is changing rapidly.\ntop\nexternal linkvibrio cholerae o1 has been responsible for several cholera outbreaks in developing countries. during 1992, a novel serogroup, o139, caused cholera outbreaks in india and other countries in asia (1). these events have shown that serogroups other than o1 have major epidemiologic roles in cholera. v. cholerae o1 and o139 serogroups produce cholera toxin (ct), a critical virulence factor and express toxin coregulated pilus (tcp), which are responsible for secretory diarrhea and intestinal colonization, respectively. serogroups other than o1 and o139 are designated as v. cholerae non-o1, non-o139, or nonagglutinating vibrios (nags); such serogroups have >200 somatic (o) antigens (2) and mostly lack ct- and tcp-coding genes.\ntoxigenic and nontoxigenic nags have caused several diarrhea outbreaks in india and other countries, including haiti (3–6). in non–ct-producing nags, other virulence factors such as heat-stable enterotoxin (stn), hemolysin (hlya), repeat in toxin (rtx), and type 3 secretion systems (ttss) have major roles in causing infections (7). in this study, we analyzed clinical characteristics of hospitalized patients with diarrhea infected with nags and screened strains for antimicrobial drug susceptibility, virulence genes, and genetic relatedness.\nthe study\nduring 2002–2010, a total of 12,719 fecal specimens were collected, which represented every fifth hospitalized diarrhea patient at the infectious diseases hospital in kolkata and all children at the outpatient unit at b.c. roy memorial hospital for children in kolkata. fecal specimens were screened for v. cholerae and other enteric pathogens as described (8). nags were serotyped by using 206 polyclonal o antisera according to the protocol developed at the national institute of infectious diseases (tokyo, japan) (2).\nantimicrobial drug susceptibility assays were performed by using the disk diffusion method and commercially available disks (becton dickinson, sparks glencoe, md, usa), according to standards of the clinical and laboratory standards institute (9). because these standards do not include interpretive criteria for v. cholerae, breakpoints for enterobacteriaceae were adopted. escherichia coli atcc 25922 was used as a quality-control strain.\nsimplex and multiplex pcrs were performed by using published methods specific for ctxa, tcpa, rtxa, rtxc, stn, and hlya genes (classical/el tor) and the ttss-coding genes (7). pulsed-field gel electrophoresis was performed according to the pulsenet standardized protocol for v. cholerae (www.pulsenetinternational.org/sitecollectiondocuments/pfge/5.71_2009_pnetstandprotvcholerae.pdf. gel compare ii software (applied maths nv, sint-martens-latem, belgium) was used for comparison of electrophoresis patterns. this software uses a dice similarity index and contains an unweighted pair group with arithmetic mean method.\nof the 12,719 diarrhea feces specimens screened, 2,206 (17.3%) contained v. cholerae, which included v. cholerae o1 in 1,841 (83.4%), and o139 in 84 (3.8%). in the remaining 281 (12.7%) specimens, v. cholerae strains did not agglutinate with serogroups o1 or o139. this result was confirmed by species-specific ompw pcr, which included strains collected during 2003 (7). among 281 strains, 175 (62.3%) nags were the only enteric pathogen found, and 106 (37.7%) of those nags were found with other enteric pathogens. the isolation frequency of nags ranged from 1.2% to 3.2% (table 1).\nalthough v. cholerae o1 is highly prevalent in kolkata, more nags were detected than in our previous study (10). a total of 224 (79.7%) strains were categorized into 80 serogroups; the remaining 57 (20.3%) were untypeable. among typeable serogroups, 14 (6.2%) strains belonged to the o37 serogroup, and 11 (4.9%) each belonged to serogroups o6 and o34. serogroups o97 (4.5%), o11 (3.6%), and o59 (3.1%) were also identified in this study. although serogroups o11, o35, and o37 showed a lower prevalence, their prevalence was higher among patients with diarrhea in kolkata (7,10). the prevalence rate of nags (≈2%) in kolkata is similar to that in the haizhu district of guangzhou, china (11). however, the number of serogroups identified in china (26 serogroups) was less than in our study (80 serogroups).\namong age groups of patients, nags were detected mostly in patients >5 years of age (>72%) than in those <5 years of age (≈28%) (table 2). nags produce a spectrum of gastrointestinal symptoms ranging from asymptomatic infection to severe cholera-like illness or bloody diarrhea. in this study, most (70%) patients had watery diarrhea, which was similar to that for patients with cholera and those exclusively infected by nags (table 2). other clinical symptoms, such as dehydration status (22.3%) and fever (41.1%), were also high in patients with a single infection. in patients with mixed infections, bloody diarrhea (23.6%) and abdominal pain (41.5%) were the 2 major symptoms (table 2), perhaps because >1 pathogen was involved.\nmost nags were resistant to nalidixic acid (57.6%), ampicillin (55.5%), furazolidone (36.6%), and streptomycin (32.4%) and highly susceptible to gentamicin (96%), tetracycline (80%), and chloramphenicol (80.4%). during 1992–1997, antimicrobial drug resistance was high among v. cholerae isolated in kolkata (12). in this study, patterns of antimicrobial drug resistance in nags were different than those in previous reports (10,12). this finding might be caused by discontinuation of ineffective antimicrobial drugs, such as co-trimoxazole and furazolidone, rational use of fluoroquinolones, and introduction of azithromycin for treating diarrhea.\ntop\nconclusions\nunlike our previous study (7), in this study, factors involved in the virulence of nags were not comprehensively elucidated in the study region. unlike v. cholerae o1/o139, the pathogenicity of nags has been associated with >1 virulence factor (7,10). all nags lacked ctxa and el tor tcpa genes. however, 6 (2.1%) strains had the tcpa gene; in 5 of them it was the only virulence gene detected. most (94%) strains had the gene encoding el tor type hemolysin, followed by rtxa (91.4%) and rtxc (75%) genes; only 5 (1.8%) had the stn gene. the rtx family includes a group of protein toxins produced by gram-negative bacteria, including v. cholerae with hemolytic, leukotoxic, and actin cross-linking activities, which may play a role in virulence (13). in this study, prevalence of nags that have genes encoding ttss as the only virulence factor (41 cases) was higher than in bangladesh and argentina (14,15).\nfigure. . . noti restriction patterns of genomic dna of representative vibrio cholerae non-o1, non-o139 strains, kolkata, india. dendrogram was generated by using the unweighted pair group with arithmetic mean method.\nstrains containing hlya, rtxa, and rtxc genes were predominant, followed by strains containing hlya-rtxa-rtxc-ttss and hlya-rtxa genes (table 3). some gene combinations, such as hlya-rtxa-rtxc-ttss, hlya-rtxa-rtxc, and hlya-rtxa, were detected predominantly nags as the only virulence factor genes (table 3). however, there was no correlation between type of serogroup and prevalence of putative virulence gene(s). pulsed-field electrophoresis profiles of 70 strains representing the predominant serogroups showed distinct patterns (overall similarity ≈70%) (figure). there was no profile match among strains belonging to the same serogroup.\nprevalence of nags associated with severe traits of infection indicates the role of these pathogens in cholera. the pathogenic mechanism of nags is multifarious; there are several virulence factors in genetically distinct strains. on the basis of our results, current antimicrobial drug therapy in the clinical management of nag-mediated diarrhea can be continued. further epidemiologic studies are needed to determine the ecology, virulence factors, and public health role of nags.\ntop\nms devarati dutta is a doctoral candidate at the national institute of cholera and enteric diseases, kolkata, india. her main research interest is the pathogenesis and molecular biology of enteric vibrios.\ntop\nexternal linkvibrio cholerae o139 bengal first emerged during 1992 and 1993 and caused large epidemics of cholera in bangladesh, india, and neighboring countries (1–3). this new strain initially displaced the existing v. cholerae o1 strains. during 1994 to the middle of 1995, in most northern and central areas of bangladesh, the o139 vibrios were replaced by a new clone of v. cholerae o1 of the el tor biotype, whereas in the southern coastal regions the o139 vibrios continued to exist (4–6). during late 1995 and 1996, cases of cholera attributable to both v. cholerae o1 and o139 were again detected in various regions of bangladesh. since 1996, cholera in bangladesh has been caused mostly by v. cholerae o1 of the el tor biotype; only a few cases have been attributable to o139 serogroup strains. the epidemiology of cholera in bangladesh changed again recently, and a large outbreak of cholera caused predominantly by v. cholerae o139 occurred in the capital city dhaka and adjoining areas.\nfrom early march to the end of april 2002, approximately 2,350 cholera patients associated with v. cholerae o139 were admitted to the dhaka hospital of the international centre for d

In [30]:
word = word.split()

In [31]:
word

['you',
 'have',
 'cholera.',
 'cholera',
 'is',
 'caused',
 'by',
 'bacteria.',
 'its',
 'symptoms',
 'include',
 'severe',
 'runny',
 'diarrhea.',
 'vomiting',
 'is',
 'another',
 'symptom.',
 'the',
 'vomit',
 'can',
 'be',
 'watery,',
 'but',
 'also',
 'bloody.',
 'the',
 'diarrhea',
 'and',
 'vomiting',
 'results',
 'in',
 'a',
 'great',
 'deal',
 'of',
 'fluid',
 'and',
 'important',
 'nutrients',
 'being',
 'lost.',
 'this',
 'can',
 'make',
 'you',
 'very',
 'sick.',
 'cholera',
 'can',
 'be',
 'transmitted',
 'through',
 'contaminated',
 'water',
 'and',
 'food.to',
 'the',
 'editor:',
 'vibrio',
 'cholerae',
 'o1,',
 'the',
 'causative',
 'agent',
 'of',
 'cholera,',
 'has',
 '2',
 'biotypes',
 '(classical',
 'and',
 'el',
 'tor),',
 'which',
 'have',
 'traditionally',
 'been',
 'distinguished',
 'by',
 'phenotypic',
 'tests',
 'and',
 'by',
 'genetic',
 'differences',
 'in',
 'the',
 'major',
 'toxin-coregulated',
 'pilus',
 '(tcp)',
 'gene,',
 'the',
 'tcpa',
 'allele',
 'of',
 'the',
 'tcp',
 'cluster',
 '(1),',
 'the',
 'rstr',
 'region',
 '(regulatory',
 'region',
 'for',
 'phage',
 'lysogeny)',
 'of',
 'ctx',
 'phages',
 '(2),',
 'the',
 'type',
 'of',
 'cholera',
 'toxin',
 '(ct)',
 'produced,',
 'and',
 'the',
 'infection',
 'pattern',
 'of',
 'the',
 'disease',
 'they',
 'cause.',
 'however,',
 '3',
 'variants',
 'of',
 'the',
 'el',
 'tor',
 'biotype',
 'have',
 'been',
 'described',
 'recently:',
 'matlab',
 '(a',
 'place',
 'in',
 'bangladesh)',
 'variants',
 'in',
 '2002',
 '(3),',
 'which',
 'could',
 'not',
 'be',
 'biotyped',
 'because',
 'they',
 'have',
 'a',
 'mixture',
 'of',
 'both',
 'classical',
 'and',
 'el',
 'tor',
 '(4),',
 'mozambique',
 'variant',
 'in',
 '2004–2005,',
 'which',
 'has',
 'a',
 'typical',
 'el',
 'tor',
 'genome',
 'but',
 'a',
 'tandem',
 'repeat',
 'of',
 'the',
 'classical',
 'ctx',
 'prophage',
 'in',
 'the',
 'small',
 'chromosome',
 '(5),',
 'and',
 'the',
 'altered',
 'el',
 'tor',
 'type',
 '(a',
 'typical',
 'el',
 'tor',
 'biotype',
 'and',
 'an',
 'el',
 'tor',
 'ctx',
 'prophage',
 'that',
 'produces',
 'ct',
 'of',
 'the',
 'classical',
 'type)',
 'predominant',
 'in',
 'bangladesh',
 'since',
 '2001',
 '(6).',
 'hybrid',
 'vibrios',
 'have',
 'also',
 'been',
 'described',
 'in',
 'other',
 'regions',
 'of',
 'asia',
 'and',
 'africa',
 '(7).',
 'ct,',
 'encoded',
 'by',
 'the',
 'ctxa',
 'and',
 'ctxb',
 'genes,',
 'is',
 'the',
 'principal',
 'toxin',
 'produced',
 'by',
 'v.',
 'cholerae',
 'o1',
 'and',
 'o139.',
 'methods',
 'for',
 'differentiating',
 'the',
 'biotype-specific',
 'ct-b',
 'subunit',
 'of',
 'v.',
 'cholerae',
 'o1',
 'include',
 'sequencing',
 'the',
 'ctxb',
 'gene,',
 'performing',
 'an',
 'elisa',
 'wth',
 'a',
 'monoclonal',
 'antibody',
 'specific',
 'to',
 'the',
 'classical',
 'or',
 'el',
 'tor',
 'ct,',
 'or',
 'by',
 'using',
 'a',
 'mismatch',
 'amplification',
 'mutation',
 'assay',
 '(mama)–pcr',
 'to',
 'distinguish',
 'between',
 '2',
 'kinds',
 'of',
 'ctxb',
 'genes.',
 'this',
 'assay',
 'detects',
 'sequence',
 'polymorphisms',
 'based',
 'on',
 'nt',
 'position',
 '203',
 'of',
 'the',
 'ctxb',
 'gene',
 '(8).',
 'in',
 'punjab',
 'and',
 'haryana',
 'states',
 'of',
 'northern',
 'india,',
 'during',
 'july–september',
 '2007,',
 '6',
 'clusters',
 'of',
 'cholera',
 'outbreak',
 'were',
 'identified.',
 'a',
 'total',
 'of',
 '745',
 'case-patients',
 'were',
 'admitted',
 'to',
 'local',
 'government',
 'hospitals;',
 'the',
 'cholera',
 'attack',
 'rate',
 'was',
 '183/1,000',
 'population.',
 'four',
 'deaths',
 'were',
 'reported',
 '(case-fatality',
 'rate',
 '0.5%).',
 'the',
 'number',
 'of',
 'cases',
 'per',
 'cluster',
 'varied',
 'from',
 '15',
 'to',
 '400,',
 'and',
 'adults',
 'were',
 'primarily',
 'affected',
 '(74%);',
 '20%',
 'of',
 'patients',
 'had',
 'severe',
 'dehydration.',
 'v.',
 'cholerae',
 'o1',
 'ogawa',
 'was',
 'confirmed',
 'from',
 'stool',
 'cultures',
 'by',
 'using',
 'standard',
 'isolation,',
 'biochemical,',
 'and',
 'serotyping',
 'methods.',
 'twenty-six',
 'isolates',
 'were',
 'phenotypically',
 'and',
 'genotypically',
 'characterized',
 'according',
 'to',
 'biotype.',
 'phenotypic',
 'characterization',
 'included',
 'the',
 'voges-proskauer',
 'reaction,',
 'polymyxin',
 'b',
 '(50',
 'u)',
 'susceptibility,',
 'chick',
 'cell',
 'agglutination,',
 'and',
 'sheep',
 'erythrocyte',
 'hemolysis;',
 'all',
 'isolates',
 'were',
 'confirmed',
 'as',
 'el',
 'tor',
 'biotype.',
 'genotypic',
 'characterization',
 'included',
 'pcr',
 'assays',
 'for',
 'ctxa',
 'and',
 'tcpa',
 '(2),',
 'rstr',
 '(3),',
 'and',
 'ctxb',
 '(8).',
 'all',
 'strains',
 'were',
 'toxigenic',
 'because',
 'each',
 'carried',
 'the',
 'ctxa',
 'gene.',
 'all',
 'strains',
 'also',
 'carried',
 'el',
 'tor–specific',
 'tcpa',
 '(472',
 'bp)',
 'and',
 'rstr',
 'genes',
 '(500',
 'bp).',
 'mama-pcr',
 'showed',
 'the',
 'ctxb',
 'gene',
 'of',
 'both',
 'el',
 'tor',
 'and',
 'the',
 'classical',
 'type',
 'in',
 '21',
 '(80%)',
 'of',
 '26',
 'isolates',
 'tested.',
 'similarly,',
 'we',
 'also',
 'tested',
 '20',
 'available',
 'isolates',
 'from',
 'the',
 '2002',
 'outbreak',
 'and',
 '4',
 'and',
 '19',
 'sporadic',
 'isolates',
 'from',
 '2003',
 'and',
 '2004,',
 'respectively;',
 'all',
 'were',
 'phenotypically',
 'and',
 'genotypically',
 'confirmed',
 'as',
 'el',
 'tor',
 'and',
 'had',
 'only',
 'ctxb',
 'of',
 'the',
 'el',
 'tor',
 'type.',
 'of',
 '53',
 'water',
 'samples',
 'tested',
 'during',
 'the',
 '2007',
 'outbreak,',
 '4',
 'grew',
 'v.',
 'cholerae.',
 'three',
 'samples',
 'were',
 'confirmed',
 'to',
 'be',
 'non-o1,',
 'non-o139',
 'strains.',
 'only',
 '1',
 'isolate',
 'was',
 'v.',
 'cholerae',
 'o1,',
 'which',
 'was',
 'positive',
 'for',
 'tcp,',
 'ctxa,',
 'and',
 'ctxb',
 'of',
 'both',
 'classical',
 'and',
 'el',
 'tor',
 'types',
 '(table).',
 'during',
 'the',
 'cholera',
 'outbreak',
 'of',
 '2002',
 'in',
 'chandigarh',
 '(9),',
 'only',
 '1',
 'death',
 'was',
 'reported',
 '(case-fatality',
 'rate,',
 '<0.01%);',
 'the',
 'attack',
 'rate',
 'was',
 '20/1,000,',
 '58.6%',
 'were',
 'children,',
 'and',
 'only',
 '10%',
 'had',
 'severe',
 'dehydration.',
 'before',
 'the',
 'most',
 'recent',
 'outbreak,',
 'the',
 'affected',
 'regions',
 'of',
 'panjab',
 'and',
 'haryana',
 '(ambala,',
 'nurpur,',
 'kurali,',
 'mohali,',
 'panchkula,',
 'and',
 'raili)',
 'had',
 'been',
 'free',
 'of',
 'cholera',
 'outbreaks',
 'since',
 '1994,',
 'though',
 'sporadic',
 'cases',
 'had',
 'been',
 'reported.',
 'the',
 '4',
 'deaths',
 'from',
 'cholera',
 'in',
 '2007,',
 'along',
 'with',
 'adult',
 'preponderance,',
 'high',
 'attack',
 'rate,',
 'more',
 'severe',
 'illness,',
 'and',
 '6',
 'different',
 'clusters,',
 'point',
 'towards',
 'a',
 'change',
 'in',
 'the',
 'disease’s',
 'epidemiology.',
 'this',
 'change',
 'may',
 'be',
 'related',
 'to',
 'circulation',
 'of',
 'the',
 'hybrid',
 'vibrios',
 'in',
 'this',
 'region.',
 'in',
 'bangladesh,',
 'all',
 'strains',
 'of',
 'v.',
 'cholerae',
 'o1',
 'examined',
 'since',
 '2001',
 'belong',
 'to',
 'the',
 'altered',
 'el',
 'tor',
 'type',
 '(6),',
 'which',
 'produces',
 'ct',
 'of',
 'the',
 'classical',
 'type.',
 'this',
 'altered',
 'type',
 'has',
 'replaced',
 'the',
 'seventh',
 'pandemic',
 'strain',
 'of',
 'the',
 'el',
 'tor',
 'biotype',
 'that',
 'produced',
 'ct',
 'of',
 'the',
 'el',
 'tor',
 'type,',
 'which',
 'indicates',
 'that',
 'a',
 'cryptic',
 'change',
 'has',
 'occurred',
 'in',
 'the',
 'seventh',
 'pandemic',
 'el',
 'tor',
 'biotype',
 'strains',
 'of',
 'v.',
 'cholerae',
 'o1.',
 'newly',
 'emerged',
 'variants',
 'from',
 'bangladesh',
 '(8)',
 'have',
 'the',
 'genetic',
 'makeup',
 'of',
 'el',
 'tor',
 'with',
 'ctxb',
 'gene',
 'of',
 'only',
 'classical,',
 'whereas',
 'our',
 'strains',
 'are',
 'unique',
 'in',
 'having',
 'ctxb',
 'of',
 'both',
 'the',
 'classical',
 'and',
 'el',
 'tor',
 'biotypes.',
 'our',
 'strains',
 'appear',
 'to',
 'be',
 'different',
 'from',
 'the',
 'mozambique',
 'variant',
 'v.',
 'cholerae',
 'o1',
 '(10),',
 'which',
 'has',
 'rstr',
 'of',
 'the',
 'classical',
 'type,',
 'in',
 'that',
 'our',
 'strains',
 'have',
 'rstr',
 'of',
 'only',
 'the',
 'el',
 'tor',
 'type.',
 'of',
 '5',
 'matlab',
 'variants',
 'analyzed',
 'with',
 'mama-pcr,',
 '3',
 'had',
 'classical',
 'ctxb',
 'and',
 '2',
 'had',
 'el',
 'tor',
 'type.',
 'our',
 'study',
 'highlights',
 'the',
 'different',
 'genetic',
 'recombinations',
 'possible',
 'in',
 'v.',
 'cholerae',
 'and',
 'the',
 'epidemiologic',
 'role',
 'of',
 'these',
 'recombinations.',
 'top',
 'external',
 'linkto',
 'the',
 'editor.',
 'cholera,',
 'caused',
 'by',
 'vibrio',
 'cholerae,',
 'continues',
 'to',
 'affect',
 'millions',
 'of',
 'persons',
 'in',
 'disease-endemic',
 'areas',
 'where',
 'safe',
 'drinking',
 'water',
 'is',
 'scarce',
 'and',
 'sanitation',
 'is',
 'poor.',
 'of',
 '7',
 'cholera',
 'pandemics',
 'recorded',
 'since',
 '1817,',
 'v.',
 'cholerae',
 'serogroup',
 'o1',
 'classical',
 '(cl)',
 'biotype',
 'was',
 'associated',
 'with',
 'the',
 'sixth,',
 'whereas',
 'the',
 'seventh',
 '(ongoing)',
 'pandemic',
 'was',
 'initiated',
 'by',
 'v.',
 'cholerae',
 'o1',
 'biotype',
 'el',
 'tor',
 '(et),',
 'which',
 'displaced',
 'cl',
 'in',
 'the',
 'early',
 '1960s',
 '(1).',
 'during',
 '1992–1993,',
 'a',
 'v.',
 'cholerae',
 'non-o1',
 'serogroup,',
 'designated',
 'v.',
 'cholerae',
 'o139',
 'synonym',
 'bengal,',
 'initiated',
 'cholera',
 'epidemics',
 'in',
 'india',
 'and',
 'bangladesh',
 'by',
 'transiently',
 'displacing',
 'v.',
 'cholerae',
 'o1',
 'et',
 'biotype',
 '(2).',
 'v.',
 'cholerae',
 'o139',
 'was',
 'less',
 'frequently',
 'associated',
 'with',
 'cholera',
 'in',
 'bangladesh',
 'than',
 'v.',
 'cholerae',
 'et',
 'in',
 '1994',
 'and',
 'the',
 'years',
 'following,',
 'until',
 '2005',
 '(3);',
 'it',
 'has',
 'been',
 'undetected',
 'since',
 'then.',
 'meanwhile,',
 'v.',
 'cholerae',
 'et',
 'has',
 'shown',
 'genetic',
 'changes',
 'since',
 '2001,',
 'and',
 ...]

In [32]:
len(word)

15453

In [33]:
word_set = set(word)

In [34]:
len(word_set)

2288

In [35]:
from collections import Counter
word_counts = Counter(word)

print(word_counts.most_common(50))

[('the', 879), ('of', 642), ('and', 539), ('in', 433), ('to', 245), ('were', 227), ('strains', 226), ('cholerae', 220), ('v.', 217), ('a', 194), ('o139', 168), ('with', 166), ('by', 151), ('from', 131), ('el', 127), ('was', 125), ('cholera', 124), ('for', 122), ('tor', 114), ('o1', 100), ('that', 91), ('this', 90), ('isolated', 81), ('as', 77), ('have', 73), ('classical', 63), ('during', 62), ('which', 61), ('at', 61), ('bangladesh', 58), ('has', 56), ('ctxb', 56), ('type', 52), ('is', 51), ('gene', 50), ('all', 50), ('epidemic', 50), ('been', 47), ('recent', 47), ('these', 43), ('ctx', 42), ('genetic', 41), ('cases', 40), ('are', 40), ('nags', 40), ('had', 39), ('using', 38), ('patients', 38), ('genes', 37), ('associated', 37)]

## Clean Articles

In [36]:
import re

def clean_text(text, source):


    if source == "CDC":
        text = re.sub(r"ISSN: 1080-6059\n(.*?)\n(.*?)\n", "", text, flags=re.DOTALL)
        text = re.sub(r"\nAcknowledgment\n.*", "", text, flags=re.DOTALL)
        text = re.sub(r"This Article$", "", text)
        text = re.sub(r"(\(\d+\))", "", text, flags=re.IGNORECASE)

    elif source == "MedlinePlus":
        text = re.sub(r"You Are Here:\nHome → (.*?) →(.*?)\n", "", text, flags=re.DOTALL)
        text = re.sub(r"\nLearn More\n.*", "", text, flags=re.DOTALL)

    text = re.sub(r"\nTop\n", "", text, flags=re.IGNORECASE)
    text = re.sub(r"(Figure|Fig\.?)\s*\d+[^\n]*", "", text)
    text = re.sub(r"(Table|Tab\.?)\s*\d+[^\n]*", "", text)


    text = re.sub(r"(Acknowledgment|References|External Links).*", "", text, flags=re.DOTALL | re.IGNORECASE)
    text = re.sub(r"(on this page|cite this article|article metrics|downloads|table downloads)", "", text, flags=re.IGNORECASE)
    text = re.sub(r"to the editor:?", "", text, flags=re.IGNORECASE)

    text = re.sub(r"\t", " ", text)
    text = re.sub(r"\s+", " ", text)
    text = text.strip(".")
    text = text.strip()
    text = re.sub(r"\n+", "\n", text)
    text = text.lower()


    noise_words = [
        "pubmed", "google scholar", "external link",
        "related links", "advanced article search",
        "comments", "send to", "editors"
    ]

    for word in noise_words:
        text = re.sub(rf"\b{word}\b", "", text)


    text = re.sub(r"[^a-z0-9.,!?():\-\s/%+°]", " ", text)


    text = re.sub(r"\s+", " ", text)
    text = "Source: " + source + " Article: " + text
    return text.strip()

In [37]:
for index, row in data.iterrows():
    cleaned_articles = []
    for article in row['Article']:
        cleaned_article = clean_text(article["content"], article['source'])
        cleaned_articles.append(cleaned_article)
    
    data.at[index, 'Article'] = cleaned_articles

In [38]:
import json

with open("diseases.json", "w", encoding="utf-8") as f:
    json.dump(data.to_dict(orient="records"), f, ensure_ascii=False, indent=4)

## Chunking and metadata

In [104]:
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_experimental.text_splitter import SemanticChunker

embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

splitter = SemanticChunker(
    embeddings,
    breakpoint_threshold_type="percentile",
    breakpoint_threshold_amount=0.5
    )

In [105]:
def chunk_text(text, splitter, overlap_size=1):
    chunks = splitter.split_text(text)
    new_chunks = []

    for i in range(len(chunks)):
        chunk = chunks[i]

        if i > 0:
            prev_part = chunks[i-1].split()[-overlap_size:]
            chunk = " ".join(prev_part) + " " + chunk

        new_chunks.append(chunk)

    return new_chunks

In [106]:
all_chunks = []

for row in data.itertuples():
    disease = row.Disease
    chapter = row.Chapter
    domain = row.Domain

    for article in row.Article:
        chunks = chunk_text(article, splitter, overlap_size=10)
        for c in chunks:
            all_chunks.append({
                "text": c.strip(),
                "metadata": {
                "disease": disease,
                "chapter": chapter,
                "domain": domain,
                }
            })

In [107]:
all_chunks

[{'text': 'Source: Federal Ministry of Health Article: you have cholera.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'Source: Federal Ministry of Health Article: you have cholera. cholera is caused by bacteria.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholera is caused by bacteria. its symptoms include severe runny diarrhea.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'its symptoms include severe runny diarrhea. vomiting is another symptom.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'vomiting is another symptom. the vomit can be watery, but also bloody. the diarrhea and vomiting results in a great deal of fluid and important nutrients being lost.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'a great deal of fluid and important nutrients being lost. this can make you very sick.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'this can make you very sick. cholera can be transmitted through contaminated water and food',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'Source: CDC Article: vibrio cholerae o1, the causative agent of cholera, has 2 biotypes (classical and el tor), which have traditionally been distinguished by phenotypic tests and by genetic differences in the major toxin-coregulated pilus (tcp) gene, the tcpa allele of the tcp cluster , the rstr region (regulatory region for phage lysogeny) of ctx phages , the type of cholera toxin (ct) produced, and the infection pattern of the disease they cause. however, 3 variants of the el tor biotype have been described recently: matlab (a place in bangladesh) variants in 2002 , which could not be biotyped because they have a mixture of both classical and el tor , mozambique variant in 2004 2005, which has a typical el tor genome but a tandem repeat of the classical ctx prophage in the small chromosome , and the altered el tor type (a typical el tor biotype and an el tor ctx prophage that produces ct of the classical type) predominant in bangladesh since 2001 .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'of the classical type) predominant in bangladesh since 2001 . hybrid vibrios have also been described in other regions of asia and africa .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'been described in other regions of asia and africa . ct, encoded by the ctxa and ctxb genes, is the principal toxin produced by v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'and ctxb genes, is the principal toxin produced by v. cholerae o1 and o139.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholerae o1 and o139. methods for differentiating the biotype-specific ct-b subunit of v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'methods for differentiating the biotype-specific ct-b subunit of v. cholerae o1 include sequencing the ctxb gene, performing an elisa wth a monoclonal antibody specific to the classical or el tor ct, or by using a mismatch amplification mutation assay (mama) pcr to distinguish between 2 kinds of ctxb genes.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': '(mama) pcr to distinguish between 2 kinds of ctxb genes. this assay detects sequence polymorphisms based on nt position 203 of the ctxb gene .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'based on nt position 203 of the ctxb gene . in punjab and haryana states of northern india, during july september 2007, 6 clusters of cholera outbreak were identified.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'july september 2007, 6 clusters of cholera outbreak were identified. a total of 745 case-patients were admitted to local government hospitals the cholera attack rate was 183/1,000 population.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'local government hospitals the cholera attack rate was 183/1,000 population. four deaths were reported (case-fatality rate 0.5%).',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'four deaths were reported (case-fatality rate 0.5%). the number of cases per cluster varied from 15 to 400, and adults were primarily affected (74%) 20% of patients had severe dehydration.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'were primarily affected (74%) 20% of patients had severe dehydration. v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'v. cholerae o1 ogawa was confirmed from stool cultures by using standard isolation, biochemical, and serotyping methods.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'stool cultures by using standard isolation, biochemical, and serotyping methods. twenty-six isolates were phenotypically and genotypically characterized according to biotype.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'twenty-six isolates were phenotypically and genotypically characterized according to biotype. phenotypic characterization included the voges-proskauer reaction, polymyxin b (50 u) susceptibility, chick cell agglutination, and sheep erythrocyte hemolysis all isolates were confirmed as el tor biotype.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'erythrocyte hemolysis all isolates were confirmed as el tor biotype. genotypic characterization included pcr assays for ctxa and tcpa , rstr , and ctxb .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'for ctxa and tcpa , rstr , and ctxb . all strains were toxigenic because each carried the ctxa gene.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'all strains were toxigenic because each carried the ctxa gene. all strains also carried el tor specific tcpa (472 bp) and rstr genes (500 bp).',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'tor specific tcpa (472 bp) and rstr genes (500 bp). mama-pcr showed the ctxb gene of both el tor and the classical type in 21 (80%) of 26 isolates tested.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'the classical type in 21 (80%) of 26 isolates tested. similarly, we also tested 20 available isolates from the 2002 outbreak and 4 and 19 sporadic isolates from 2003 and 2004, respectively all were phenotypically and genotypically confirmed as el tor and had only ctxb of the el tor type.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'tor and had only ctxb of the el tor type. of 53 water samples tested during the 2007 outbreak, 4 grew v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'water samples tested during the 2007 outbreak, 4 grew v. cholerae.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholerae. three samples were confirmed to be non-o1, non-o139 strains.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'three samples were confirmed to be non-o1, non-o139 strains. only 1 isolate was v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'only 1 isolate was v. cholerae o1, which was positive for tcp, ctxa, and ctxb of both classical and el tor types (table).',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'and ctxb of both classical and el tor types (table). during the cholera outbreak of 2002 in chandigarh , only 1 death was reported (case-fatality rate, 0.01%) the attack rate was 20/1,000, 58.6% were children, and only 10% had severe dehydration.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': '20/1,000, 58.6% were children, and only 10% had severe dehydration. before the most recent outbreak, the affected regions of panjab and haryana (ambala, nurpur, kurali, mohali, panchkula, and raili) had been free of cholera outbreaks since 1994, though sporadic cases had been reported.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholera outbreaks since 1994, though sporadic cases had been reported. the 4 deaths from cholera in 2007, along with adult preponderance, high attack rate, more severe illness, and 6 different clusters, point towards a change in the disease s epidemiology.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'clusters, point towards a change in the disease s epidemiology. this change may be related to circulation of the hybrid vibrios in this region.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'related to circulation of the hybrid vibrios in this region. in bangladesh, all strains of v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'in bangladesh, all strains of v. cholerae o1 examined since 2001 belong to the altered el tor type , which produces ct of the classical type.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'tor type , which produces ct of the classical type. this altered type has replaced the seventh pandemic strain of the el tor biotype that produced ct of the el tor type, which indicates that a cryptic change has occurred in the seventh pandemic el tor biotype strains of v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'in the seventh pandemic el tor biotype strains of v. cholerae o1.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholerae o1. newly emerged variants from bangladesh have the genetic makeup of el tor with ctxb gene of only classical, whereas our strains are unique in having ctxb of both the classical and el tor biotypes.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'having ctxb of both the classical and el tor biotypes. our strains appear to be different from the mozambique variant v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'strains appear to be different from the mozambique variant v. cholerae o1 , which has rstr of the classical type, in that our strains have rstr of only the el tor type.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'our strains have rstr of only the el tor type. of 5 matlab variants analyzed with mama-pcr, 3 had classical ctxb and 2 had el tor type.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': '3 had classical ctxb and 2 had el tor type. our study highlights the different genetic recombinations possible in v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'our study highlights the different genetic recombinations possible in v. cholerae and the epidemiologic role of these recombinations.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'Source: CDC Article: cholera, caused by vibrio cholerae, continues to affect millions of persons in disease-endemic areas where safe drinking water is scarce and sanitation is poor.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'where safe drinking water is scarce and sanitation is poor. of 7 cholera pandemics recorded since 1817, v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'of 7 cholera pandemics recorded since 1817, v. cholerae serogroup o1 classical (cl) biotype was associated with the sixth, whereas the seventh (ongoing) pandemic was initiated by v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'sixth, whereas the seventh (ongoing) pandemic was initiated by v. cholerae o1 biotype el tor (et), which displaced cl in the early 1960s .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'tor (et), which displaced cl in the early 1960s . during 1992 1993, a v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'during 1992 1993, a v. cholerae non-o1 serogroup, designated v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholerae non-o1 serogroup, designated v. cholerae o139 synonym bengal, initiated cholera epidemics in india and bangladesh by transiently displacing v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholera epidemics in india and bangladesh by transiently displacing v. cholerae o1 et biotype .',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'cholerae o1 et biotype . v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},
 {'text': 'v. cholerae o139 was less frequently associated with cholera in bangladesh than v.',
  'metadata': {'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae',
   'chapter': 'Certain infectious and parasitic diseases',
   'domain': 'Intestinal infectious diseases'}},

## Embeeding

In [112]:
from sentence_transformers import SentenceTransformer
import faiss

def create_embedding_index(all_chunks, model):
    
    texts = [item["text"] for item in all_chunks]

    embeddings = model.encode(texts)
    faiss.normalize_L2(embeddings)
    return embeddings, texts

## Build Index

In [113]:
import numpy as np
def create_faiss_index(embeddings):
    embeddings = np.array(embeddings).astype('float32')
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(embeddings.shape[1])
    index.add(np.array(embeddings))
    return index

## Search Through Index

In [114]:
def search(query, index, model, k=1):
    query_vec = model.encode([query])
    faiss.normalize_L2(query_vec)
    scores, ids = index.search(np.array(query_vec), k)
    return scores, ids

## Using Rag Functions

In [115]:
import numpy as np
query = "What is Cholera due to Vibrio cholerae 01, biovar cholerae?"

model = "all-MiniLM-L6-v2"
model = SentenceTransformer(model).to("cuda")

embeddings, texts = create_embedding_index(all_chunks, model)
index = create_faiss_index(embeddings)
scores, ids = search(query, index, model, k=3)

for idx in ids[0]:
    print(all_chunks[idx]["text"])
    print(all_chunks[idx]["metadata"])

c:\Users\User\anaconda3\envs\ml_env\lib\site-packages\huggingface_hub\file_download.py:942: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

cholerae o1 et and 4 v. cholerae o139).
{'disease': 'Cholera due to Vibrio cholerae 01, biovar eltor', 'chapter': 'Certain infectious and parasitic diseases', 'domain': 'Intestinal infectious diseases'}
cholerae o1 et and 4 v. cholerae o139).
{'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae', 'chapter': 'Certain infectious and parasitic diseases', 'domain': 'Intestinal infectious diseases'}
v. cholerae strains a total of 63 v.
{'disease': 'Cholera due to Vibrio cholerae 01, biovar cholerae', 'chapter': 'Certain infectious and parasitic diseases', 'domain': 'Intestinal infectious diseases'}

## Record a Question

In [116]:
import sounddevice as sd
from scipy.io.wavfile import write
import numpy as np

def record_audio(filename="input.wav", duration=5, fs=16000, channels=1):
    print("Speak now...")

    audio = sd.rec(int(duration * fs), samplerate=fs, channels=channels)
    sd.wait()

    audio = np.int16(audio * 32767)

    write(filename, fs, audio)

## Cleaning Voice

In [50]:
import librosa
import numpy as np

def clean_audio(file):
    y, sr = librosa.load(file, sr=16000)
    y = librosa.effects.preemphasis(y)
    return y

## Converting Question Record into Text

In [51]:
import whisper
whisper_model = whisper.load_model("medium")

def speech_to_text(filename="input.wav", model=whisper_model):
    file = clean_audio(filename)
    time.sleep(2)
    result = model.transcribe(file, fp16=False, language="en", temperature=0, initial_prompt="Medical assistant conversation")
    return result["text"]

## Ask ollama

In [68]:
import requests

def ask_ollama(prompt):
    response = requests.post(
        "http://localhost:11434/api/generate",
        json={
           "model": "llama3:8b",
           "prompt": prompt,
           "stream": False,
           "temperature": 0.0
        }
    )
    
    return response.json()['response']

## Converting Answer Into Speech with Piper

In [53]:
import re

def humanize_text(text):
    
    text = re.sub(r"[*|#|-|_]", "", text)

    text = text.replace("\n", ". ")

    text = text.replace(",", ", ... ")
    
    text = text.replace(".", ". ... ")

    text = re.sub(r"\s+", " ", text).strip()

    return text

In [54]:
import os
import subprocess

PIPER_PATH = r"C:\Users\User\AppData\Local\Programs\piper\piper.exe"
MODEL_PATH = r"C:\Users\User\AppData\Local\Programs\piper\en_US-amy-medium.onnx"
OUTPUT_FILE = "output.wav"

def text_to_speech_piper(text):
    process = subprocess.run(
        [
            PIPER_PATH,
            "--model", MODEL_PATH,
            "--output_file", OUTPUT_FILE,
            "--length_scale", "1.2"
        ],
        input=text,
        text=True
    )

    os.system(f"start {OUTPUT_FILE}")

## Converting Answer into Speech with gTTs

In [55]:
from gtts import gTTS
import os

def text_to_speech_gtts(text):
    tts = gTTS(text)
    tts.save("response.mp3")
    os.system("start response.mp3")

## Using Speech_text and Text_speech functions

In [58]:
record_audio()

text = speech_to_text()
print("Human:", text)


answer = ask_ollama(prompt=text)
print("AI Answer:", answer)

text_to_speech_piper(answer)

Speak now...
Human:  Medical assistant conversation
AI Answer: Here's a sample conversation for a medical assistant:

**Patient:** Hi, I'm here for my annual physical. I've been feeling a bit fatigued lately and wanted to get checked out.

**Medical Assistant (MA):** Okay! Let me just get your chart real quick. (checks the patient's chart) Alright, everything looks good so far. Can you tell me more about what you mean by fatigue? Is it constant or does it come and go?

**Patient:** It's been pretty consistent. I've been feeling like I need to take a nap every day around 2-3 pm.

**MA:** Okay, that doesn't sound normal at all! Have you noticed any other symptoms like pain or difficulty sleeping?

**Patient:** Actually, yeah... sometimes my joints ache and I have trouble falling asleep at night. And my hair has been falling out in clumps lately.

**MA:** Whoa, okay! That does sound concerning. Let me go get the doctor to come take a look. (gets the doctor)

**Doctor:** Hi there! So, what's going on? You mentioned fatigue and some other symptoms...

**Patient:** Yeah... I just want to make sure everything is okay.

**Doctor:** Okay, well let's take a look at you real quick. (performs a physical examination) Hmm, your blood pressure is a bit high and your pulse is irregular. I'm going to order some tests to rule out any underlying conditions. We'll also need to get you set up with an appointment with a specialist.

**Patient:** Okay... what kind of tests?

**MA:** (interrupting) Don't worry about that right now, we'll take care of all the testing and arrangements. The doctor will discuss everything with you once we have more information. In the meantime, I'm going to go ahead and schedule your appointment with the specialist.

**Patient:** Sounds good... thanks for taking care of this.

In this conversation, the medical assistant:

* Greeted the patient and verified their identity
* Asked questions to clarify the patient's symptoms and concerns
* Recorded the patient's information in their chart
* Notified the doctor that the patient was ready to be seen
* Assisted with the physical examination (although not shown here)
* Helped facilitate communication between the patient and doctor

## Build Memory

In [164]:
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_community.chat_message_histories import ChatMessageHistory
from langchain_core.prompts import ChatPromptTemplate

store = {}

def get_session_history(session_id):
    if session_id not in store:
        store[session_id] = ChatMessageHistory()
    return store[session_id]

## disease Confidence

In [165]:
from collections import defaultdict
import numpy as np

def disease_confidence(ids, scores, all_chunks):
    disease_scores = defaultdict(list)

    for i, idx in enumerate(ids[0]):
        disease = all_chunks[idx]["metadata"]["disease"]
        disease_scores[disease].append(scores[0][i])
    final_scores = {
        disease: np.mean(vals)
        for disease, vals in disease_scores.items()
    }

    return sorted(final_scores.items(), key=lambda x: x[1], reverse=True)

## NER for retrived Data

In [166]:
from transformers import pipeline
def NER_extract(text, ner):
    entites = ner(text)
    return entites

## Filter Entities

In [167]:
def filter_entities(entities, label):
    return [
        e["word"] for e in entities
        if e["entity_group"] == label and e["score"] > 0.8
    ]

## Retrieve Context

In [168]:
def retrieve_context(query, index, model, k=3):
    scores, ids = search(query, index, model, k)

    texts = []
    metas = []

    for i in ids[0]:
        texts.append(all_chunks[i]["text"])
        metas.append(all_chunks[i]["metadata"])

    return texts, metas, scores, ids

## Process Context

In [169]:
def process_context(texts, ner, query):
    context = "\n\n".join(texts)

    context_entities = NER_extract(context, ner)
    query_entities = NER_extract(query, ner)

    return {
        "context": context,
        "context_symptoms": list(set(filter_entities(context_entities, "Sign_symptom"))),
        "query_symptoms": list(set(filter_entities(query_entities, "Sign_symptom"))),
        "context_diseases": list(set(filter_entities(context_entities, "Disease"))),
        "query_diseases": list(set(filter_entities(query_entities, "Disease"))),
    }

## Build a prompt

In [183]:
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder


def build_prompt():

    prompt = ChatPromptTemplate.from_messages([
        ("system",
        """
You are MedAssistant, a medical AI assistant.

IMPORTANT RULES:

INTENT:
- First detect the intent: (definition / diagnosis / symptoms / cause / advice)

REASONING:
- Use ONLY the provided context and extracted entities
- Prioritize extracted symptoms over raw text
- Do NOT assume or add missing symptoms
- If symptoms are insufficient → say uncertainty
- Prefer diseases supported by multiple symptoms
- Each disease must include a confidence percentage
- Explain reasoning briefly using matched symptoms

DIAGNOSIS:
- Do NOT return symptoms as diagnosis
- Return top 2–3 possible diseases
- Rank by likelihood using provided confidence

OUTPUT:
- Be concise (2–3 sentences max)
- Use natural spoken language (no bullet points or symbols)
- Keep explanation short and clear
- If multiple diseases share similar symptoms, mention this uncertainty

SAFETY:
- Do NOT provide definitive diagnosis
- Do NOT suggest medications
- If serious condition suspected → advise seeking medical help

FALLBACK:
- If answer not in context → say:
"The answer is not clearly available in the context."
        """
         ),
          MessagesPlaceholder(variable_name="history"),
        ("human",
         """

CONTEXT:
{context}

Symptoms (context):
{context_symptoms}

Diseases (context):
{context_diseases}

User symptoms:
{query_symptoms}

User diseases:
{query_diseases}

Disease likelihood:
{disease_conf}

QUESTION:
{query}

Answer clearly and concisely.
""")
    ])

    return prompt

## Test the whole Proccess

In [187]:
from langchain_ollama import ChatOllama

query = "what is cholera hi how are you doing today my name is ahmed and i want to know about cholera please tell me about cholera and its symptoms and causes and how can i treat it"

context_texts, context_metas, scores, ids = retrieve_context(query, index, model, k=3)

ner = pipeline("ner", model="d4data/biomedical-ner-all", aggregation_strategy="simple")

context_data = process_context(context_texts, ner, query)
disease_conf = disease_confidence(ids, scores, all_chunks)


prompt = build_prompt()

In [ ]:
disease_conf[0]

NameError: name 'disease_conf' is not defined

:

In [175]:
llm = ChatOllama(
    model="llama3:8b",
    temperature=0
)

chain = prompt | llm

In [176]:
from langchain_core.runnables.history import RunnableWithMessageHistory

chain_with_memory = RunnableWithMessageHistory(
    chain,
    get_session_history,
    input_messages_key="query",
    history_messages_key="history"
)

In [182]:
response = chain_with_memory.invoke(

    {
        "query": query,
        "context": context_data["context"],
        "context_symptoms": context_data["context_symptoms"],
        "context_diseases": context_data["context_diseases"],
        "query_symptoms": context_data["query_symptoms"],
        "query_diseases": context_data["query_diseases"],
        "disease_conf": disease_conf,
    },

    config={
        "configurable": {
            "session_id": "user_1"
        }
    }
)

print(response.content)

Your name is Abdelrahman.

In [178]:
print(response)

content="Hello Abdelrahman! As MedAssistant, I'm here to help you with any medical concerns or questions you may have.\n\nBased on the context provided, it seems like we're discussing a research study conducted at icddr,b in Dhaka during March-April 2002. The study focused on isolating Vibrio cholerae from stool samples.\n\nIf you'd like to discuss your symptoms or any health concerns you might be experiencing, please feel free to share them with me. I'll do my best to provide guidance and support.\n\nRemember, as a medical AI assistant, everything discussed remains confidential and for informational purposes only." additional_kwargs={} response_metadata={'model': 'llama3:8b', 'created_at': '2026-05-28T00:35:32.7143901Z', 'done': True, 'done_reason': 'stop', 'total_duration': 30898824800, 'load_duration': 121880500, 'prompt_eval_count': 203, 'prompt_eval_duration': 1011887500, 'eval_count': 128, 'eval_duration': 29640047500, 'logprobs': None, 'model_name': 'llama3:8b', 'model_provider': 'ollama'} id='lc_run--019e6c01-8e35-7f13-ae4d-2e3873a9acf6-0' tool_calls=[] invalid_tool_calls=[] usage_metadata={'input_tokens': 203, 'output_tokens': 128, 'total_tokens': 331}

## Get latitude and longitude

In [71]:
from winsdk.windows.devices.geolocation import Geolocator

async def get_coords():
    locator = Geolocator()
    pos = await locator.get_geoposition_async()
    return pos.coordinate.point.position.latitude, pos.coordinate.point.position.longitude

In [72]:
lat, lng = await get_coords()
print(f"latitude: {lat}, longitude: {lng}")

latitude: 30.466870789335562, longitude: 30.925501498349064

## Get closest hospital or clinic

In [73]:
def get_closest_facilities_safe(lat, lon, radius=20000):
    overpass_url = "https://overpass-api.de/api/interpreter"
    
    headers = {
        'User-Agent': 'Medical_Assistant',
        'Referer': 'https://overpass-turbo.eu/'
    }

    query = f"""
    [out:json][timeout:25];
    (
      node["amenity"~"hospital|clinic"](around:{radius}, {lat}, {lon});
      way["amenity"~"hospital|clinic"](around:{radius}, {lat}, {lon});
    );
    out center;
    """
    
    try:
        response = requests.get(overpass_url, params={'data': query}, headers=headers, timeout=30)
        
        if response.status_code == 200:
            data = response.json()
            return data 
        else:
            return f"{response.status_code}: {response.text}"
            
    except Exception as e:
        return e

In [74]:
closest_facilities = get_closest_facilities_safe(lat, lng, radius=10000)
closest_facilities

{'version': 0.6,
 'generator': 'Overpass API 0.7.62.11 87bfad18',
 'osm3s': {'timestamp_osm_base': '2026-05-26T12:24:00Z',
  'copyright': 'The data included in this document is from www.openstreetmap.org. The data is made available under ODbL.'},
 'elements': [{'type': 'node',
   'id': 12043578527,
   'lat': 30.4679512,
   'lon': 30.9299433,
   'tags': {'addr:housenumber': '2',
    'addr:street': 'شارع الزراعه',
    'amenity': 'clinic',
    'name': 'Dr Diaa Nour Dental Clinic'}}]}

## format data and calculate distance

In [75]:
import geopandas as gpd
from shapely.geometry import Point
from pyproj import Geod

def process_overpass_results(data, user_lat, user_lon):
    elements = data.get('elements', [])

    features = []
    geod = Geod(ellps="WGS84")

    for elem in elements:
        if elem['type'] == 'node':
            e_lon, e_lat = elem['lon'], elem['lat']
        elif 'center' in elem:
            e_lon, e_lat = elem['center']['lon'], elem['center']['lat']
        else:
            continue
            
        _, _, distance = geod.inv(user_lon, user_lat, e_lon, e_lat)
        
        tags = elem.get('tags', {})
        name = tags.get('name', tags.get('name:ar', 'Unnamed Facility'))
        hospital_type = tags.get('amenity', 'hospital')
        
        features.append({
            'Name': name, 
            'Distance (km)': round(distance / 1000, 2),
            'Type': hospital_type,
        })

    gdf = gpd.GeoDataFrame(features)
    gdf = gdf.sort_values(by='Distance (km)').reset_index(drop=True)
    return gdf

In [76]:
final_hospitals = process_overpass_results(closest_facilities, lat, lng)
final_hospitals

                         Name  Distance (km)    Type
0  Dr Diaa Nour Dental Clinic           0.44  clinic

## Web Search

In [ ]:
from langchain_community.utilities import SerpAPIWrapper
google_search = SerpAPIWrapper(serpapi_api_key="f80974fb65334f54c4f50b1f7ca6bd5b17d90cdaf2a93c7094ffeb8bc96adcd8")

def web_search(query: str):
    """Search inside a specific website."""
    trusted_query = f"""
    site:who.int OR
    site:cdc.gov OR
    site:nih.gov OR
    site:mayoclinic.org OR
    site:pubmed.ncbi.nlm.nih.gov
    {query}
    """
    return google_search.run(trusted_query)

In [201]:
print(web_search("What is fever?"))

["A fever is a temporary rise in body temperature. It's one part of an overall response from the body's immune system. A fever is usually caused by an infection.", 'In physiological terms, fever has been defined as “a state of elevated core temperature, which is often, but not necessarily, part of the defensive response of ...', "Fever, or pyrexia, is the elevation of an individual's core body temperature above a 'set-point' regulated by the body's thermoregulatory center in the ...", "A fever is a rise in body temperature. It's often a sign of infection. Fever itself most often is harmless and it may play a role in ...", 'A fever (has a measured temperature of 100.4 °F [38 °C] or greater, or feels warm to the touch, or gives a history of feeling feverish) ...', 'Fever, an elevation above normal body temperature, is a frequent symptom of many infections [1]. It results from the release of endogenous pyrogens such as ...', 'A raised temperature is considered to be a fever at 38.5°C (101.3°F) or more in children, and at 38.0°C (100.4°F) or more in babies under three ...', 'Fatigue and warmth are found to be the most prevalent symptoms during febrile phase. Associated symptoms can help in predicting the intensity of fever also.', "Medications can lower a fever, but sometimes it's better left untreated. Fever may play a role in helping your body fight off infections.", 'Fever works by causing more damage to pathogens and infected cells than it does to healthy cells in the body. During pandemic COVID-19, the benefits of allowing ...']

In [1]:
query = "What is Cholera due to Vibrio cholerae 01, biovar cholerae?"

In [10]:
from transformers import pipeline

classifier = pipeline(
    "zero-shot-classification",
    model="typeform/distilbert-base-uncased-mnli"
)

labels = [
    "medical diagnosis",
    "disease definition",
    "hospital search",
    "emergency",
    "general advice",
    "chatting"
]

query = "I have diarrhea and vomiting"

result = classifier(query, labels)

intent = result["labels"][0]

print(intent)
print(result)

The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.
The `xla_device` argument has been deprecated in v4.4.0 of Transformers. It is ignored and you can safely remove it from your `config.json` file.

disease definition
{'sequence': 'I have diarrhea and vomiting', 'labels': ['disease definition', 'emergency', 'medical diagnosis', 'chatting', 'hospital search', 'general advice'], 'scores': [0.45056766271591187, 0.2224290817975998, 0.19331596791744232, 0.059128887951374054, 0.04305300489068031, 0.03150537982583046]}

In [25]:
result = classifier("what is the nearest clinic?", labels)

intent = result["labels"][0]

In [26]:
intent

'medical diagnosis'

In [32]:
from langchain_community.utilities import SerpAPIWrapper
google_search = SerpAPIWrapper(serpapi_api_key="f80974fb65334f54c4f50b1f7ca6bd5b17d90cdaf2a93c7094ffeb8bc96adcd8")

def drug_search(query: str):
    """Search for drug information."""
    trusted_query = f"""
    site:mayoclinic.org OR
    site:nlm.nih.gov OR
    site:nhs.uk/medicines OR
    site:open.fda.gov/apis/drug OR
    site:dailymed.nlm.nih.gov
    {query}
    """
    return google_search.run(trusted_query)

In [30]:
drugs = drug_search("medicine for fever")

In [ ]:
import sounddevice as sd
import numpy as np
import queue

SAMPLE_RATE = 16000
BLOCK_SIZE = 1024

audio_queue = queue.Queue()


def callback(indata, frames, time, status):
    audio_queue.put(indata.copy())


def record_until_silence():
    print("🎤 Listening...")

    silence_threshold = 0.01
    silence_frames = 0
    max_silence = 60  

    audio_buffer = []
    speaking_started = False

    with sd.InputStream(samplerate=SAMPLE_RATE,
                        channels=1,
                        callback=callback,
                        blocksize=BLOCK_SIZE):

        while True:
            audio = audio_queue.get()
            audio_float = audio[:, 0]

            volume = np.abs(audio_float).mean()

            if volume > silence_threshold:
                speaking_started = True
                silence_frames = 0
                audio_buffer.append(audio_float)

            else:
                if speaking_started:
                    silence_frames += 1
                    audio_buffer.append(audio_float)

            if speaking_started and silence_frames > max_silence:
                break

    print("🛑 Stopped")

    return np.concatenate(audio_buffer)

In [4]:
import whisper

model = whisper.load_model("medium")

def transcribe(audio):
    result = model.transcribe(audio, fp16=False)
    return result["text"]

In [9]:
record = record_until_silence()

🎤 Listening...
🛑 Stopped

In [10]:
record

array([-0.00061035, -0.00021362, -0.0005188 , ...,  0.00073242,
        0.00256348,  0.003479  ], dtype=float32)

In [11]:
result = model.transcribe(record, fp16=False)

text = result["text"]

In [12]:
text

" Hi, how are you today? I'm talking to you about cholera. Cholera is a bacteria that causes dehydration and causes many symptoms also. So today we are going to discuss this disease."

In [ ]:
import sounddevice as sd
import numpy as np
import whisper

# ================= CONFIG =================
SAMPLE_RATE = 16000
BLOCK_SIZE = 1024

SILENCE_THRESHOLD = 0.01   # حساسية الصوت
MAX_SILENCE_FRAMES = 30    # ~1 ثانية سكوت

# ================= LOAD WHISPER =================
model = whisper.load_model("base")


# ================= RECORD FUNCTION =================
def record_until_silence():
    print("🎤 Listening... speak now")

    audio_buffer = []
    silence_counter = 0
    speaking_started = False

    def callback(indata, frames, time, status):
        nonlocal audio_buffer, silence_counter, speaking_started

        audio = indata[:, 0]

        volume = np.abs(audio).mean()

        # detect speech
        if volume > SILENCE_THRESHOLD:
            speaking_started = True
            silence_counter = 0
            audio_buffer.append(audio.copy())

        else:
            if speaking_started:
                silence_counter += 1
                audio_buffer.append(audio.copy())

    with sd.InputStream(
        samplerate=SAMPLE_RATE,
        channels=1,
        callback=callback,
        blocksize=BLOCK_SIZE
    ):
        while True:
            sd.sleep(100)

            # stop condition
            if speaking_started and silence_counter > MAX_SILENCE_FRAMES:
                break

    print("🛑 Recording stopped")

    if len(audio_buffer) == 0:
        return None

    return np.concatenate(audio_buffer)


# ================= TRANSCRIBE =================
def speech_to_text():
    audio = record_until_silence()

    if audio is None:
        return ""

    print("🧠 Transcribing...")

    result = model.transcribe(audio, fp16=False)

    text = result["text"]

    print("📝 You said:", text)

    return text


# ================= RUN =================
if __name__ == "__main__":
    while True:
        query = speech_to_text()

        if query.strip():
            print("➡️ FINAL TEXT:", query)